DATASET:
  DATASET: 'pascal_voc'
  DATA_PATH: './datasets'

TRAINING:
  NUM_THREADS: 16
  BATCH_SIZE: 32
  BATCH_SIZE_ON_1_GPU: 4
  NUM_EPOCHS: 200
  MAX_LR: 1e-4
  EVAL_FREQ: 1

MODEL:
  MODEL_TYPE: 'upernet'
  BINARY_TYPE: 'bidense'
  NUM_CLASSES: 22
